services:
  db:
    container_name: db
    image: dbimage
    ports:
      - "3306:3306"

  auth_service:
    container_name: auth_service
    image: authimage
    ports:
      - "5001:5001"

  book_service:
    container_name: book_service
    image: bookimage
    ports:
      - "5002:5002"

  borrow_service:
    container_name: borrow_service
    image: borrowimage
    ports:
      - "5003:5003"

  frontend:
    container_name: frontend
    image: frontendimage
    ports:
      - "5000:5000"
